-- MySQL Script generated by MySQL Workbench
-- 10/10/18 16:00:42
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema paybackalarmclock
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `paybackalarmclock` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `paybackalarmclock` ;

-- -----------------------------------------------------
-- Table `paybackalarmclock`.`plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paybackalarmclock`.`plan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `money` INT NOT NULL,
  `day` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paybackalarmclock`.`excute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paybackalarmclock`.`excute` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `plan` INT NOT NULL,
  `periods` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL,
  `overdue` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_e_p_idx` (`plan` ASC),
  CONSTRAINT `fk_e_p`
    FOREIGN KEY (`plan`)
    REFERENCES `paybackalarmclock`.`plan` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
